### PR TITLE
fix: detect name collisions and provide fallback call function

### LINKED ISSUE #494: Name collision on similar names
**Describe the bug**

We can reliably cause compiler errors within the Elixir project using this library, for the elixir modules generated from the proto files, by using similar-enough function names.

Internally to this project, `rpc` names are not used directly, but are normalized using the function [Macro.underscore/1](https://hexdocs.pm/elixir/1.12/Macro.html#underscore/1) before the function block is generated.

**To Reproduce**

Define a service that has `rpc` names that collide after a call to `Macro.underscore/1`, shown below in protos.

The service will build through `protocol` correctly, but when compiling the Elixir project, there will be a compiler error on the generated elixir file on the line `use GRPC.Stub, service: ...`.  Due to calls [like this](https://github.com/elixir-grpc/grpc/blob/master/grpc_client/lib/grpc/stub.ex#L69) the two different `npc` definitions map to the same elixir function internally, but each are defined.

**Expected behavior**

`process_data` and `ProcessData` are distinct function names within grpc and protobuf.  While they violate both grpc best practices and elixir best practices, they pass `protocol` checks and compile to multiple language outputs.  If we had to use a proto that defined `rpc` calls in this way, we should be able to.

**Logs**
If applicable, add logs to help explain your problem.

When compiling the generated elixir modules, I receive the error:
```bash
error: def process_data/3 defines defaults multiple times. Elixir allows defaults to be declared once per definition. Instead of:

    def foo(:first_clause, b \\ :default) do ... end
    def foo(:second_clause, b \\ :default) do ... end

one should write:

    def foo(a, b \\ :default)
    def foo(:first_clause, b) do ... end
    def foo(:second_clause, b) do ... end

<generated_ex_file>:<line_number>
```

**Protos**
If applicable, add protos to help explain your problem.

Have a service defined with function names that are similar to each other:
```proto

message Request {
  string data = 1;
}

message Response {
  string result = 1;
}

service SimilarService {
  rpc process_data (Request) returns (Response) {}
  rpc ProcessData (Request) returns (Response) {}
}
```

**Versions:**
- OS: OSX 
- Erlang: 26.1.2
- Elixir: 1.15.7
- mix.lock(grpc, gun, cowboy, cowlib):
```bash
❯ mix deps
* bunt 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (bunt) dc5f86aa
  ok
* cowboy 2.14.2 (Hex package) (rebar3)
  locked at 2.14.2 (cowboy) 569081da
  ok
* cowlib 2.16.0 (Hex package) (rebar3)
  locked at 2.16.0 (cowlib) 7f478d80
  ok
* credo 1.7.13 (Hex package) (mix)
  locked at 1.7.13 (credo) 47641e6d
  ok
* dialyxir 1.4.7 (Hex package) (mix)
  locked at 1.4.7 (dialyxir) b3452720
  ok
* earmark_parser 1.4.44 (Hex package) (mix)
  locked at 1.4.44 (earmark_parser) 4778ac75
  ok
* erlex 0.2.8 (Hex package) (mix)
  locked at 0.2.8 (erlex) 9d66ff9f
  ok
* ex_doc 0.39.1 (Hex package) (mix)
  locked at 0.39.1 (ex_doc) 8abf0ed3
  ok
* file_system 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (file_system) 7a15ff97
  ok
* flow 1.2.4 (Hex package) (mix)
  locked at 1.2.4 (flow) 874adde9
  ok
* gen_stage 1.3.2 (Hex package) (mix)
  locked at 1.3.2 (gen_stage) 0ffae547
  ok
* googleapis 0.1.0 (Hex package) (mix)
  locked at 0.1.0 (googleapis) 1989a724
  ok
* grpc 0.11.5 (Hex package) (mix)
  locked at 0.11.5 (grpc) 0a5d8673
  ok
* gun 2.2.0 (Hex package) (rebar3)
  locked at 2.2.0 (gun) 76022700
  ok
* hpax 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (hpax) 8eab6e1c
  ok
* jason 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (jason) c5eb0cab
  ok
* makeup 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (makeup) d3648486
  ok
* makeup_elixir 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (makeup_elixir) 7284900d
  ok
* makeup_erlang 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (makeup_erlang) af33ff7e
  ok
* mint 1.7.1 (Hex package) (mix)
  locked at 1.7.1 (mint) fceba0a4
  ok
* nimble_parsec 1.4.2 (Hex package) (mix)
  locked at 1.4.2 (nimble_parsec) 4b213989
  ok
* protobuf 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (protobuf) 5d7bb325
  ok
* ranch 2.2.0 (Hex package) (rebar3)
  locked at 2.2.0 (ranch) fa0b99a1
  ok
* telemetry 1.3.0 (Hex package) (rebar3)
  locked at 1.3.0 (telemetry) 7015fc89
  ok
```

**Additional context**

This is not a blocker for me, I discovered it while looking for corner cases in a related library.  It seems like it should be unlikely, but I wanted to call it out anyways.

I checked the output for Python and C++, and they both _appeared_ to have the original names in the files but then again so do we:

```elixir
defmodule EdgeCases.SimilarService.Service do
  @moduledoc false

  use GRPC.Service, name: "edge_cases.SimilarService", protoc_gen_elixir_version: "0.14.1"

  def descriptor do
    # credo:disable-for-next-line
    %Google.Protobuf.ServiceDescriptorProto{
      name: "SimilarService",
      method: [
        %Google.Protobuf.MethodDescriptorProto{
          name: "process_data",
          input_type: ".edge_cases.Request",
          output_type: ".edge_cases.Response",
          options: %Google.Protobuf.MethodOptions{
            deprecated: false,
            idempotency_level: :IDEMPOTENCY_UNKNOWN,
            features: nil,
            uninterpreted_option: [],
            __pb_extensions__: %{},
            __unknown_fields__: []
          },
          client_streaming: false,
          server_streaming: false,
          __unknown_fields__: []
        },
        %Google.Protobuf.MethodDescriptorProto{
          name: "ProcessData",
          input_type: ".edge_cases.Request",
          output_type: ".edge_cases.Response",
          options: %Google.Protobuf.MethodOptions{
            deprecated: false,
            idempotency_level: :IDEMPOTENCY_UNKNOWN,
            features: nil,
            uninterpreted_option: [],
            __pb_extensions__: %{},
            __unknown_fields__: []
          },
          client_streaming: false,
          server_streaming: false,
          __unknown_fields__: []
        }
      ],
      options: nil,
      __unknown_fields__: []
    }
  end

  rpc :process_data, EdgeCases.Request, EdgeCases.Response

  rpc :ProcessData, EdgeCases.Request, EdgeCases.Response
end

defmodule EdgeCases.SimilarService.Stub do
  @moduledoc false

  use GRPC.Stub, service: EdgeCases.SimilarService.Service
end
```

It is the line `use GRPC.Stub` in `defmodule EdgeCases.SimilarService.Stub do` that is generating the error.  You can see in `EdgeCases.SimilarService.Service` that the `npc` headers correctly define the two cases separately: 
```elixir
  rpc :process_data, EdgeCases.Request, EdgeCases.Response
  rpc :ProcessData, EdgeCases.Request, EdgeCases.Response
```

I haven't tried to run a grpc project using the Python or C++ output; so there is even a chance it's broken everywhere and we could simply use a better error message.

### PR DESCRIPTION
**Pull request by polvalente**
closes #494

### CODE REVIEW

File: grpc_client/test/grpc/integration/endpoint_test.exs [hunk 1]
```diff
@@ -72,7 +72,7 @@ defmodule GRPC.Integration.EndpointTest do
                {:ok, reply} = channel |> Helloworld.Greeter.Stub.say_hello(req)
                assert reply.message == "Hello, Elixir"
              end)
-           end) =~ "GRPC.Integration.EndpointTest.HelloServer.say_hello"
+           end) =~ "GRPC.Integration.EndpointTest.HelloServer.SayHello"
```
Comment (polvalente) [inline grpc_client/test/grpc/integration/endpoint_test.exs]: Gotta work to not have these changes. The functions that have non-fallback clauses should print the same here

**Comment by sleipnir** [comment]
I think the test is failing because of the added warning.

File: grpc_client/lib/grpc/stub.ex [hunk 2]
```diff
@@ -58,15 +58,44 @@ defmodule GRPC.Stub do
...
+        #{collision_details}
+
+        Conflicting RPC functions will not be generated. Instead, use the general
+        `call/3` or `call/4` function with the original RPC name as the first argument.
+
+        Example:
+
+            YourStub.call(:OriginalRpcName, channel, request, opts)
+            YourStub.call(:original_rpc_name, channel, request, opts)
+        """)
```
Comment (sleipnir) [inline grpc_client/lib/grpc/stub.ex:93]: In addition to the example, I would like to point to the gRPC conventions documentation.
https://protobuf.dev/programming-guides/style/
